title: JS Maps
email: jbennett@webrapids.com
description: Just a collection of JavaScript Maps to demonstrate power libraries like leaflet and connecting data on the web to generate cool visualizations.